cfs registration

diff --git a/sources/cfs-registration b/sources/cfs-registration
--- a/sources/cfs-registration
+++ b/sources/cfs-registration
@@ -1,14 +1,14 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          cfs-registration
 # Required-Start:    $network $local_fs $remote_fs $syslog
 # Required-Stop:
 # Default-Start:     2 3 4 5
-# Default-Stop:
+# Default-Stop:		 0 1 6
 # Short-Description: Register your Raspy to cfs board.
 ### END INIT INFO
 
-PATH=/sbin:/bin
+PATH=/sbin:/bin:/usr/bin
 SERIAL=$(cat /proc/cpuinfo | grep Serial | cut -d":" -f2 | tr -d ' ')
 MAC=$(cat /sys/class/net/eth0/address)
 REGISTRATION_SERVICE=https://coding-for-school-boards.herokuapp.com/register
@@ -38,8 +38,24 @@ case "$1" in
 
 	[ "$VERBOSE" = no ] || log_action_end_msg $ES
 	;;
-  *)
-	echo "Usage: cfs-registration start" >&2
+
+  stop)
+	# No-op
+	;;
+
+  restart|reload|force-reload)
+	echo "Error: argument '$1' not supported" >&2
 	exit 3
 	;;
+
+  status)
+	do_status
+	exit $?
+	;;
+
+  *)
+	echo "Usage: cfs-registration [start|stop|status]" >&2
+	exit 3
+	;;
+
 esac
