cfs registration

diff --git a/sources/cfs-registration b/sources/cfs-registration
--- a/sources/cfs-registration
+++ b/sources/cfs-registration
@@ -1,13 +1,45 @@
-#!/bin/bash
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          cfs-registration
+# Required-Start:    $network $local_fs $remote_fs $syslog
+# Required-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:
+# Short-Description: Register your Raspy to cfs board.
+### END INIT INFO
 
-serial=$(cat /proc/cpuinfo | grep Serial | cut -d":" -f2 | tr -d ' ')
-mac=$(cat /sys/class/net/eth0/address)
-registration_service=https://coding-for-school-boards.herokuapp.com/register
+PATH=/sbin:/bin
+SERIAL=$(cat /proc/cpuinfo | grep Serial | cut -d":" -f2 | tr -d ' ')
+MAC=$(cat /sys/class/net/eth0/address)
+REGISTRATION_SERVICE=https://coding-for-school-boards.herokuapp.com/register
 
-if [ -z "$serial" ]; then
-  echo "CPU Serial not found. Using mac address"
-  serial=$mac
-fi
+#. /lib/init/vars.sh
+#. /lib/lsb/init-functions
 
-curl -s $registration_service/$serial > /dev/null
 
+case "$1" in
+  start|"")
+	[ "$VERBOSE" = no ] || log_action_begin_msg "Registering to cfs board"
+	##
+	SERIAL=$RANDOM$RANDOM$RANDOM
+
+	if [ -z "$SERIAL" ]; then
+	  echo "CPU Serial not found. Using mac address"
+	  SERIAL=$MAC
+	fi
+
+	#curl -s $REGISTRATION_SERVICE/$SERIAL > /dev/null
+	curl -s $REGISTRATION_SERVICE/$SERIAL
+	ES=$?
+	##
+	ECHO "out ->"
+	ECHO $ES
+	ECHO "!DONE!"
+
+	[ "$VERBOSE" = no ] || log_action_end_msg $ES
+	;;
+  *)
+	echo "Usage: cfs-registration start" >&2
+	exit 3
+	;;
+esac
